# H2
spring.h2.console:
  enabled: true
  path: /h2

# Datasource
spring.datasource:
  url: jdbc:h2:./stations

#JPA
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: create # update, none, validate, update, create, create-drop
  properties.hibernate.format_sql: true

# Java 8 time
spring.jackson:
    serialization.write_dates_as_timestamps: false