# H2
spring.h2.console:
  enabled: true
  path: /h2

# Datasource
spring.datasource:
  url: jdbc:h2:./stations

#JPA
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: create # update, none, validate, update, create, create-drop